import type { Product } from "./product";

export const categories = [
  { name: "Electronic", imageUrl: "/cat-electronic.webp" },
  { name: "Tools", imageUrl: "/cat-tools.jpg" },
  { name: "Home", imageUrl: "/cat-home.webp" },
  { name: "Clothes", imageUrl: "/cat-clothes.jpg" },
];

export const popularProducts: Product[] = [
  {
    prodName: "Sweater",
    price: "10",
    vendorName: "LTB",
    imageUrl: "kazak.jpg",
    prodId: "1",
    category: "Clothes",
  },
  {
    prodName: "Washing Machine",
    price: "350",
    vendorName: "Beko",
    imageUrl: "camasirmak.png",
    prodId: "2",
    category: "Home",
  },
  {
    prodName: "Playstation 4",
    price: "399",
    prevPrice: "587",
    vendorName: "Sony",
    imageUrl: "playstation.jpg",
    prodId: "3",
    category: "Electronic",
  },
  {
    prodName: "Drill",
    price: "120",
    vendorName: "Bosch",
    imageUrl: "matkap.jpg",
    prodId: "4",
    category: "Tools",
  },
];

export const saleProducts: Product[] = [
  {
    prodName: "Carpet",
    price: "30",
    prevPrice: "90",
    vendorName: "Allinsare",
    imageUrl: "hali.jpg",
    prodId: "5",
    category: "Home",
  },
  {
    prodName: "Lenovo Ideapad 4",
    price: "240",
    prevPrice: "440",
    vendorName: "Lenovo",
    imageUrl: "laptop.jpg",
    prodId: "6",
    category: "Electronic",
  },
  {
    prodName: "Hair Dryer",
    price: "38",
    prevPrice: "50",
    vendorName: "Sinbo",
    imageUrl: "fonmak.jpeg",
    prodId: "7",
    category: "Home",
  },
  {
    prodName: "Beret",
    price: "20",
    prevPrice: "30",
    vendorName: "DeFacto",
    imageUrl: "bere.jpeg",
    prodId: "8",
    category: "Clothes",
  },
];

export const products: Product[] = [
  ...popularProducts,
  ...saleProducts,

  {
    prodName: "Jordan",
    price: "300",
    vendorName: "Nike",
    imageUrl: "ayakkabi.png",
    prodId: "9",
    category: "Clothes",
  },
  {
    prodName: "Socks",
    price: "300",
    vendorName: "Nike",
    imageUrl: "corap.jpeg",
    prodId: "10",
    category: "Clothes",
  },
  {
    prodName: "Coffee Machine",
    price: "600",
    vendorName: "Bosch",
    imageUrl: "kahvemak.jpg",
    prodId: "11",
    category: "Home",
  },
  {
    prodName: "Lock",
    price: "3",
    vendorName: "Kale",
    imageUrl: "kilit.jpg",
    prodId: "12",
    category: "Tools",
  },
  {
    prodName: "Stall",
    price: "120",
    vendorName: "Bellona",
    imageUrl: "koltuk.jpg",
    prodId: "13",
    category: "Home",
  },
  {
    prodName: "Victus 15",
    price: "450",
    prevPrice: "600",
    vendorName: "HP",
    imageUrl: "Laptop.png",
    prodId: "14",
    category: "Electronic",
  },
  {
    prodName: "Desk",
    price: "220",
    prevPrice: "320",
    vendorName: "Bellona",
    imageUrl: "masa.jpg",
    prodId: "15",
    category: "Home",
  },
  {
    prodName: "Jeans",
    price: "32",
    prevPrice: "36",
    vendorName: "Mavi",
    imageUrl: "pantolon.jpeg",
    prodId: "16",
    category: "Clothes",
  },
  {
    prodName: "Socket",
    price: "2",
    prevPrice: "5",
    vendorName: "Viko",
    imageUrl: "priz.jpeg",
    prodId: "17",
    category: "Tools",
  },
  {
    prodName: "Iphone 15 Pro Max",
    price: "1200",
    prevPrice: "1400",
    vendorName: "Apple",
    imageUrl: "telefon.jpg",
    prodId: "18",
    category: "Electronic",
  },
  {
    prodName: "TV",
    price: "650",
    prevPrice: "800",
    vendorName: "LG",
    imageUrl: "Tv.png",
    prodId: "19",
    category: "Electronic",
  },
  {
    prodName: "T-Shirt",
    price: "40",
    prevPrice: "70",
    vendorName: "Nike",
    imageUrl: "tisort.webp",
    prodId: "20",
    category: "Clothes",
  },
];
